---
- name: add apt key
  apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc

- name: add apt repo
  apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main
    update_cache: yes

- name: install core stuff
  apt: name={{ item }} state=present
  with_items:
    - postgresql-9.4
    - postgresql-contrib-9.4
    - libpq-dev
